<?xml version="1.0"?> 
<!DOCTYPE bookstore [ 
<!ELEMENT bookstore (book)> 
<!ELEMENT book (bookname,bookprice,bookauthor,booknumber,pages)> 
<!ELEMENT bookname (#PCDATA)> 
<!ELEMENT bookprice (#PCDATA)> 
<!ELEMENT bookauthor (#PCDATA)> 
<!ELEMENT booknumber (#PCDATA)> 

<!ELEMENT pages (#PCDATA)> 
]> 
<bookstore>
<book>
<bookname>the complete work</bookname>
<bookauthor>aaaa</bookauthor>
<bookprice>$300</bookprice>
<ISBN>98765</ISBN>
<pages>800</pages>
</book>
<book>
<bookname>mahabaratham</bookname>
<bookauthor>bbbb</bookauthor>
<bookprice>$800</bookprice>
<ISBN>98543</ISBN>
<pages>1000</pages>
</book>
<book>
<bookname>stories</bookname>
<bookauthor>cccc</bookauthor>
<bookprice>$1000</bookprice>
<ISBN>98345</ISBN>
<pages>600</pages>
</book>
<book>
<bookname>ramayaan</bookname>
<bookauthor>valmiki</bookauthor>
<bookprice>$900</bookprice>
<ISBN>98675</ISBN>
<pages>1500</pages>
</book>
<book>
<bookname>Maths</bookname>
<bookauthor>rmanujanam</bookauthor>
<bookprice>$500</bookprice>
<ISBN>98875</ISBN>
<pages>1200</pages>
</book>
</bookstore>
